name: McKoth
version: ${project.version}
main: com.virtualparticle.mc.mckoth.McKoth
api-version: 1.16
depend: [WorldEdit]
authors: [VirtualParticle]
description: Minecraft King of the Hill
website: https://github.com/VirtualParticle
commands:
  kothMap:
    aliases: [kmap, km]
    description: Create and modify KOTH maps
    usage: /<command> [list|info|create|delete|add|complete] [...]
  koth:
    description: Join and leave KOTH maps
    usage: /<command> [join|leave|start] [map]